### ISSUE TITLE
Add a link to your presentation slides to the README

### ISSUE THREAD

**Issue by bittner** [jcassee/registronavale#3]
## Current State

In the [README](https://github.com/jcassee/registronavale/blob/master/readme.md) there is only a general link to the PyCon 7 website. A link to [your presentation slides](http://slides.com/jcassee/pycon-sette-hypermedia/) is missing.
## Suggested Improvements

May be handy for visitors of the repo to find a direct link to the slides, and to the video once it goes online.

**Comment by jcassee** [comment]
Done!
